language: cpp
compiler:
  - gcc
  - clang
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - libgtest-dev
env:
  - VARIANT=debug
  - VARIANT=release
script:
  - make
  - make GTEST_PREFIX=/usr test
